global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8002']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8004']

  - job_name: 'nginx-proxy-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113'] 

